spring:
  application:
    name: purchase
  data:
    mongodb:
      database: purchase
      host: ${MONGODB_HOST:192.168.99.100}
      port: 27017
      username: admin
      password: password
      