spring:
  datasource:
    url: jdbc:postgresql://db-warranty.localhost.squaretrade.com:5432/warranty?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: admin
    password: freel00k
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql